config/routes.rb
Jobrunner::Application.routes.draw do
  devise_for :users
  root to: redirect("/contacts")

  resources :activities
  resources :notes
  resources :contacts do
    member do
      get :edit_section
      patch :update_section
      get :new_invite
      post :re_invite
      post :invite
    end
  end

  resources :companies do
    member do
      get :edit_section
      patch :update_section
      patch :delete_company_logo
    end

    resources :contacts
  end
  
  namespace "api" do
    resources :company_types, defaults: { format: "json" }
    resources :companies, defaults: { format: "json" }
  end
end

app/views/user_invitations/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{ "data-dismiss" => "modal", type: "button" } ×
      %h2.modal-title
        Add a user account

    #modal-form
      = form_for [@contact, @user], html: { class: "form-horizontal" }, remote: true do |f|
        .modal-body
          - if @user.errors.any?
            .alert.alert-danger
              %a.close{ "data-dismiss" => "alert", href: "#" } ×
              - @user.errors.full_messages.each do |message|
                %p
                  = message
          .row
            .col-md-10.col-md-offset-1
              .row
                .form-group
                  .col-md-10
                    = f.text_field :email, placeholder: "Email", class: "form-control"

        .modal-footer
          %button.btn.btn-default{ "data-dismiss" => "modal", type: "button" } Close
          = f.submit "Save", class: "btn btn-primary", data: { toggle: "button", "loading-text" => "Saving" }

app/views/user_invitations/new.js.haml
$('#page-modal').html('#{j(render("new"))}').modal();

app/views/user_invitations/success.js.haml
Turbolinks.visit('#{contact_url(@contact)}');