config/routes.rb
Jobrunner::Application.routes.draw do
  devise_for :users
  root to: redirect("/contacts")

  resources :activities
  resources :notes
  resources :contacts do
    member do
      get :edit_section
      patch :update_section
      get :new_invite
      post :re_invite
      post :invite
    end
  end

  resources :companies do
    member do
      get :edit_section
      patch :update_section
      patch :delete_company_logo
    end

    resources :contacts
  end
  
  namespace "api" do
    resources :company_types, defaults: { format: "json" }
    resources :companies, defaults: { format: "json" }
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  extend Enumerize
  include Archivable
  include Audited

  validates :first_name ,presence: true
  validates :last_name, presence: true
  validates :company_id, presence: true

  belongs_to :company
  belongs_to :user
  has_many :addresses, -> { order "created_at ASC" }, dependent: :destroy, as: :addressable
  has_many :notes, -> { order "created_at DESC" }, dependent: :destroy, as: :notable
  has_many :emails, -> { order "created_at ASC" }, as: :emailable, dependent: :destroy
  has_many :phone_numbers, -> { order "created_at ASC" }, as: :phonable, dependent: :destroy
  has_and_belongs_to_many :contact_sources

  enumerize :prefix, in: %i(Mr. Mrs. Ms. Miss. Prof.)
  accepts_nested_attributes_for :notes
  accepts_nested_attributes_for :addresses, reject_if: lambda { |address| address[:address_line_1].blank? }, allow_destroy: true
  accepts_nested_attributes_for :emails, reject_if: lambda { |email| email[:value].blank? }, allow_destroy: true
  accepts_nested_attributes_for :phone_numbers, reject_if: lambda { |phone_number| phone_number[:phone_number].blank? }, allow_destroy: true

  def full_name
    [self.first_name, self.middle_name, self.last_name].compact.join(" ")
  end

  class << self
    def search(term)
      return Contact.none if term.blank?
      term_like = "%#{term}%"
      includes(:company).references(:company).where("first_name ILIKE ? OR last_name ILIKE ? OR concat(first_name, last_name) ILIKE ? OR companies.name ILIKE ?", term_like, term_like, term_like.gsub(/\s/, ""), term_like)
    end

    def eager_load_associations
      includes(:addresses, :notes, :emails, :phone_numbers)
    end

    def with_birthday_months(month_ids)
      where('extract(month from birthday) IN (?)', month_ids)
    end

    def contacts_of_companies_with_relationship_to(internal_company_ids)
      includes(company: :internal_company_relationships).references(:internal_company_relationships).where('internal_company_relationships.internal_company_id IN (?)', internal_company_ids)
    end

    def contacts_of_companies_with_internal_relationship_role(roles)
      includes(company: :internal_company_relationships).references(:internal_company_relationships).where('internal_company_relationships.role IN (?)', roles)
    end

    def contacts_of_companies_with_company_types(company_type_ids)
      includes(:company).references(:company).where('companies.company_type_id IN (?)', company_type_ids)
    end
  end

  def to_vcf
    card = Vpim::Vcard::Maker.make2 do |maker|
      maker.add_name do |name|
        name.prefix = self.prefix if self.prefix.present?
        name.given = self.first_name
        name.family = self.last_name
      end
      maker.org = self.company.name

      self.phone_numbers.each do |phone_number|
        phone_number_str = phone_number.phone_number
        phone_number_str = "#{phone_number_str} x#{phone_number.extension}" if phone_number.extension.present?
        maker.add_tel(phone_number_str) { |t| t.location = phone_number.kind }
      end

      self.emails.each { |email| maker.add_email(email.value) }
      self.addresses.each do |address|
        maker.add_addr do |addr|
          addr.pobox = address.address_line_1
          addr.street = address.address_line_2 if address.address_line_2.present?
          addr.locality = address.city
          addr.region = address.state
          addr.country = address.country.text.upcase if address.country.present?
        end
      end
    end

    card.to_s
  end

  def audit_meta
    {
      item_descriptor: "contact #{self.full_name}",
      item_root_class: self.class,
      item_root_object_id: self.id
    }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include SearchFiltersSaver
  include AddressParamsParser

  respond_to :html, :js, :csv, :vcf
  before_filter :authenticate_admin!, only: [:new_invite, :invite, :re_invite]

  ENTITY_PREFIX = "contact"
  FILTER_ITEMS = [:a, :bm, :ct, :irr, :rc, :search, :name_sort]

  def index
    @entities, @entities_all_pages = apply_filters(@entities)
    respond_with(@entities)
  end
  
  def new
    @entity = @entities.build
    respond_with(@entity)
  end

  def create
    @entity = @entities.build(permitted_params)
    if @entity.save
      redirect_to(save_success_url)
    else
      render(:new)
    end
  end

  def edit
    render(:new)
  end

  def update
    if @entity.update_attributes(permitted_params_with_country_parsed)
      redirect_to(save_success_url)
    else
      render(:new)
    end
  end

  def show
    @entities, @entities_all_pages = apply_filters(@entities)
    set_saved_filters_new_page!
    respond_with do |format|
      format.html { respond_with(@entity) }
      format.vcf do 
        send_data(@entity.to_vcf, filename: "#{@entity.full_name}.vcf", "Content-Disposition" => "attachment",
                  "Content-type" => "text/x-vcard; charset=utf-8"
        )
      end
    end
  end

  def destroy
    @entity.destroy
    redirect_to(destroy_success_url)
  end

  def edit_section
    respond_to do |format|
      format.js { render(:edit_section) }
    end
  end

  def update_section
    if @entity.update_attributes(permitted_params)
      render(:success)
    else
      render(:edit_section)
    end
  end

  def new_invite
    @entity = Contact.find(params[:id])
    @user = @entity.build_user
    respond_with(@user)
  end

  def invite
    @entity = Contact.find(params[:id])
    @user = User.invite!({ email: params[:user][:email] }, current_user) { |user| user.contacts << @entity } 
    partial = @user.errors.present? ? :new_invite : :success_invite
    respond_to do |format|
      format.js { render(partial) }
    end
  end

  def re_invite
    @entity = Contact.find(params[:id])
    @user = User.invite!({ email: @entity.user.email }, current_user)
    flash[:success] = "The user has been re-invited successfully."
    redirect_to(contact_url(@entity))
  rescue
    flash[:danger] = "Something went wrong, try again."
    render(:show)
  end

  private

  def permitted_params
    params.require(:contact).permit(:first_name, :middle_name, :last_name, :prefix, :job_title, :company_id, :birthday,
                                    :contest_participant, :send_mmi_ballgame_emails, :do_not_mail, :do_not_email, :send_cookies, contact_source_ids: [],
                                    addresses_attributes: [:id, :address_line_1, :address_line_2, :city, :state, :zip, :country, :_destroy],
                                    emails_attributes: [:id, :value, :_destroy],
                                    phone_numbers_attributes: [:id, :extension, :kind, :phone_number, :_destroy]
    )
  end

  def user_params
    params.require(:user).permit(:email)
  end

  def destroy_success_url
    @company ? company_url(@company) : contacts_url_with_saved_filters
  end

  def load_entities
    @company = Company.find(params[:company_id]) if params[:company_id].present?
    @entities = @company ? @company.contacts : Contact.all
    @entity = @entities.find(params[:id]) if params[:id].present?
  end

  def save_success_url
    @company ? company_url(@company) : contact_url(@entity)
  end

  def apply_filters_concrete(source)
    source_filtered = get_saved_filters.has_key?(:search) ? source.search(get_saved_filters[:search]) : source
    source_filtered = source_filtered.with_archived_status(get_saved_filters[:a]) if get_saved_filters.has_key?(:a)
    source_filtered = source_filtered.with_birthday_months(get_saved_filters[:bm]) if get_saved_filters.has_key?(:bm)
    source_filtered = source_filtered.contacts_of_companies_with_company_types(get_saved_filters[:ct]) if get_saved_filters.has_key?(:ct)
    source_filtered = source_filtered.contacts_of_companies_with_internal_relationship_role(get_saved_filters[:irr]) if get_saved_filters.has_key?(:irr)

    source_filtered = source_filtered.contacts_of_companies_with_relationship_to(get_saved_filters[:rc]) if get_saved_filters.has_key?(:rc)
    source_filtered = get_saved_filters[:name_sort] == "down" ? source_filtered.order("first_name DESC") : source_filtered.order("first_name ASC")
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  include BackForwardLinkGenerator
  include CountryStateDataSource
  
  def tooltip_text_for_filter(filter)
    {
      relationships: "Shows all contacts of a company where the company is related to the selected internal company",
      roles: "Shows all contacts of a company where the company is related to an internal company in the selected role",
      status: "Shows all contacts of a company where the company has the selected affiliation or relationship status",
      company_type: "Shows all contacts of a company where the company is of the selected type",
      birthday: "Shows contacts with the selected birthday"
    }[filter]
  end

  private

  def entity_path
    ->(id) { contact_path(id) }
  end
end

app/views/contacts/_address_fields.html.haml
.row
  #addresses
    = f.fields_for :addresses, (@entity.persisted? || @entity.addresses.present?) ? @entity.addresses : @entity.addresses.build, wrapper: false do |address_form|
      .col-md-4.fields
        .panel.panel-default
          .panel-heading
            .panel-title
              Address
          .panel-body
            = address_form.input :address_line_1, as: :string, placeholder: "Address Line 1", label: false, input_html: { required: true }
            = address_form.input :address_line_2, as: :string, placeholder: "Address Line 2", label: false
            .row
              .col-md-6
                = country_state_select address_form, "contact"
                = address_form.input :city, placeholder: "City", label: false, input_html: { required: true }
              .col-md-6
                = address_form.input :zip, placeholder: "Zip", label: false, input_html: { required: true }

            = address_form.link_to_remove "Remove", class: "btn btn-danger"
  .col-md-4
    = f.link_to_add  "Add address", :addresses, class: "btn btn-default", data: { target: "#addresses" }

app/views/contacts/_contact.html.haml
%tr
  %td
    = link_to contact.full_name, contact_url(contact)
  %td
    = contact.company.name
  %td
    = contact.job_title

app/views/contacts/_edit_communications.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{ "data-dismiss" => :modal, type: :button } ×
      %h2.modal-title
        Manage Commications
    #modal-form
      = simple_nested_form_for @entity, url: update_section_contact_url(@entity), remote: true, html: { class: "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { boolean: :horizontal_boolean, check_boxes: :horizontal_radio_and_checkboxes, }  do |f|
        .modal-body
          .row
            .col-sm-10.col-sm-offset-2
              .form-group.form-inline
                %label.control-label.col-sm-3{ for: "birthday" }
                  Birthday
                .col-sm-9
                  = f.date_select :birthday, { discard_year: true, include_blank: true }, { class: "form-control" }

              = f.input :contest_participant, wrapper: :horizontal_boolean
              = f.association :contact_sources, as: :check_boxes, wrapper: :horizontal_radio_and_checkboxes
              = f.input :do_not_email
              = f.input :do_not_mail

        .modal-footer
          %button.btn.btn-default{ "data-dismiss" => :modal, type: :button } Close
          = f.submit "Save", class: "btn btn-primary", data: { toggle: :button, "loading-text" => "Saving" }

app/views/contacts/_email_fields.html.haml
.row.top-buffer-15
  #emails
    .col-md-4
      .panel.panel-default
        .panel-heading
          .panel-title
            Emails
        .panel-body
          = f.fields_for :emails, @entity.emails.present? ? @entity.emails : @entity.emails.build do |email_form|
            .row
              .form-group
                .col-md-9
                  = email_form.input :value, placeholder: "Email", label: false, input_html: { required: true }
                .col-md-3
                  = email_form.link_to_remove "Remove", class: "btn btn-danger"

          = f.link_to_add "Add email", :emails, class: "btn btn-default"

app/views/contacts/_new_invite.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{ "data-dismiss" => "modal", type: "button" } ×
      %h2.modal-title
        Add a user account

    #modal-form
      = form_for([@entity, @user], url: { action: :invite }, html: { class: "form-horizontal" }, remote: true) do |f|
        .modal-body
          - if @user.errors.any?
            .alert.alert-danger
              %a.close{ "data-dismiss" => "alert", href: "#" } ×
              - @user.errors.full_messages.each do |message|
                %p
                  = message
          .row
            .col-md-10.col-md-offset-1
              .row
                .form-group
                  .col-md-10
                    = f.text_field :email, placeholder: "Email", class: "form-control"

        .modal-footer
          %button.btn.btn-default{ "data-dismiss" => "modal", type: "button" } Close
          = f.submit "Save", class: "btn btn-primary", data: { toggle: "button", "loading-text" => "Saving" }

app/views/contacts/_phone_number_fields.html.haml
.row.top-buffer-15
  #phone_numbers
    = f.fields_for :phone_numbers, (@entity.persisted? || @entity.phone_numbers.present?) ? @entity.phone_numbers : @entity.phone_numbers.build, wrapper: false do |phone_number_form|
      .col-md-4.fields
        .panel.panel-default
          .panel-heading
            .panel-title
              Phone number
          .panel-body
            = phone_number_form.input :kind, collection: PhoneNumber.kind.options, include_blank: false, label: false
            .row
              .col-md-8
                = phone_number_form.input :phone_number, placeholder: "Phone Number", label: false, input_html: { data: "phone-number-input", autocomplete: "off", required: true }
              .col-md-4
                = phone_number_form.input :extension, placeholder: "Extension", label: false, input_html: { data: "phone-number-extension-input", autocomplete: "off" }
            = phone_number_form.link_to_remove "Remove", class: "btn btn-danger"
  .col-md-4
    = f.link_to_add  "Add phone number", :phone_numbers, class: "btn btn-default", data: { target: "#phone_numbers" }

app/views/contacts/edit_section.js.haml
$('#page-modal').html('#{j(render("edit_communications"))}').modal();

app/views/contacts/index.csv.haml
- require 'csv'

- content = CSV.generate do |csv|
  - csv << ["Prefix", "First Name", "Middle Name", "Last Name", "Primary Email", "Job Title", "Company" ,"Company Type", "Address", "Address 2", "City", "State", "Zip", "Country", "Birthday", "Do Not Email", "Do Not Mail", "Source", "Contest participant", "Primary Phone", "Notes"]
  - @entities.each do |contact|
    - address = contact.addresses.first || Address.new
    - phone_number = contact.phone_numbers.first || PhoneNumber.new
    - notes = contact.notes.present? ? contact.notes.map(&:note).join(".") : "None"
    - csv << [contact.prefix, contact.first_name, contact.middle_name, contact.last_name, contact.emails.first, contact.job_title, contact.company.name, contact.company.company_type, address.address_line_1, address.address_line_2, address.city, address.state, address.zip, address.country.upcase, contact.birthday && l(contact.birthday, format: :only_date_month), human_boolean(contact.do_not_email), human_boolean(contact.do_not_mail), contact.contact_sources.map(&:to_s).join(","), human_boolean(contact.contest_participant), phone_number, notes]

= raw content

app/views/contacts/index.html.haml
.index.content
  = render "action_panel", search_url: contacts_url, csv_export_url: contacts_url(params.merge(format: 'csv'))
  .contacts.holder
    %table.table.table-hover
      %thead
        %tr
          %th.sortable
            - if(params[:name_sort] == "down")
              = link_to contacts_url(params.merge(name_sort: "up")) do
                Name
                %i.fa.fa-angle-down
            - else
              = link_to contacts_url(params.merge(name_sort: "down")) do
                Name
                %i.fa.fa-angle-up
          %th
            Company
          %th
            Title
      %tbody#contacts-listing
        %tr
          %td.add.a.contact{ colspan: 4 }
            .wrap
              %i.fa.fa-plus
              = link_to "Add a new contact", new_contact_url
        = render @entities
    #contacts-pagination
      = paginate(@entities)
.profile.on.listing.pages
  = render "profile"

  = content_for :view_specific_filters do
    %h3.filter.header
      = link_to 'javascript:void(0)', data: { toggle: "collapse", target: "#birthdays-filter ul" } do
        Birthday
        %i.glyphicon.glyphicon-chevron-up.pull-right
        %i.glyphicon.glyphicon-chevron-down.pull-right
        = button_tag "?", data: { toggle: "tooltip", title: tooltip_text_for_filter(:birthday)}, class: "btn btn-link btn-xs filter-help"

    .filter.wrapper#birthdays-filter
      %ul.list.default.list-unstyled.in
        - Date::MONTHNAMES.compact.each_with_index do |month, index|
          - month_index = index + 1;
          %li.checkbox
            = check_box_tag "birthday_filter[month_ids]", month_index, (params[:bm] || []).include?(month_index.to_s)
            = month

  = render "companies_contacts_shared/filter_sidebar"

app/views/contacts/new.html.haml
.show.content
  .go.and.profile
    .go.back
      - if(@company)
        = link_to company_url(@company) do
          %span.glyphicon.glyphicon-chevron-left
          = "Back to #{@company.name}"
      - else
        = link_to contacts_url_with_saved_filters do
          %span.glyphicon.glyphicon-chevron-left
          Back to Contacts
    .profile
      = render "profile"

  .company.details
    %h1
      - if @entity.persisted?
        = "Edit #{@entity.full_name}"
      - else
        New Contact

    - if(@company)
      %h2
        Company:
        = @company.name

    = simple_nested_form_for [@company, @entity], html: { id: "contact_form", novalidate: false } do |f|
      .row
        .col-md-12
          %h2
            Profile
          .row
            .col-md-6
              .panel.panel-default
                .panel-heading
                  .panel-title
                    Name
                .panel-body
                  .row
                    .col-md-3
                      = f.input :prefix, collection: Contact.prefix.options, include_blank: "Prefix", label: false
                    .col-md-3
                      = f.input :first_name, placeholder: "First Name", label: false
                    .col-md-3
                      = f.input :middle_name, placeholder: "Middle Name", label: false
                    .col-md-3
                      = f.input :last_name, placeholder: "Last Name", label: false
            .col-md-5
              .panel.panel-default
                .panel-heading
                  .panel-title
                    Company Relationship
                .panel-body
                  .row
                    - if @company
                      = f.hidden_field :company_id
                    - else
                      .col-md-6
                        = f.input :company_id, collection: Company.ordered_by_name.map{ |c| [c.name, c.id] }, include_blank: "Select Company", label: false
                    .col-md-6
                      = f.input :job_title, placeholder: "Job Title", label: false

      .row.top-buffer-30
        .col-md-12
          %h2
            Contact Info
          .row
            #contact_info_errors_container
          = render "address_fields", f: f
          = render "phone_number_fields", f: f
          = render "email_fields", f: f

      %br
      .form-group
        = link_to "Back", back_url_or(contacts_url_with_saved_filters), class: "btn btn-default"
        = f.submit "Save", class: "btn btn-primary"

app/views/contacts/new_invite.js.haml
$('#page-modal').html('#{j(render("new_invite"))}').modal();

app/views/contacts/show.html.haml
.neat-row
  .show.content
    .contact.intro
      .neat-row.contact-action
        .go.back
          - if(@company)
            = link_to company_url(@company) do
              %span.glyphicon.glyphicon-chevron-left
              = "Back to #{@company.name}"
          - else
            = link_to contacts_url_with_saved_filters do
              %span.glyphicon.glyphicon-chevron-left
              Back to contacts list
        .profile-container
          = render "profile"
      .basic.contact.info
        .contact.name
          %span
            = link_to_previous_entity("Previous contact")
            %span.prefix
              = @entity.prefix
            = @entity.full_name
            = link_to_next_entity("Next contact")
          = link_to url_for([@company, @entity]), class: "btn-fam pull-right err", title: "Delete", data: { confirm: "Are you sure you want to delete the contact '#{@entity.full_name}'?", method: 'delete', toggle: "tooltip" } do
            %i.fa.fa-trash-o 
            %span.action Delete
          = link_to url_for([:edit, @company, @entity]), class: "btn-fam pull-right", title: "Edit Contact", data: { toggle: "tooltip" }  do
            %i.fa.fa-pencil
            %span.action Edit
          = link_to contact_url(@entity, format: 'vcf'), class: "btn-fam pull-right", title: "Download VCard", data: { toggle: "tooltip" } do
            %i.fa.fa-phone
            %span.action Vcard

        .secondary.contact.info.row
          .col-sm-3
            .row
              .col-sm-3
                %span.label
                  Email
              .col-sm-9
                = @entity.emails.map{ |email| mail_to(email) }.map(&:to_s).join("<br>").html_safe
          .col-sm-3
            .row
              .col-sm-3
                %span.label
                  Phone
              .col-sm-9
                = @entity.phone_numbers.map(&:to_s).join("<br>").html_safe
          .col-sm-6
            .row
              .col-sm-2
                %span.label
                  Address
              .col-sm-10
                - @entity.addresses.each do |address|
                  .address
                    = [address.address_line_1, address.address_line_2, address.city, Address.get_long_state_name(address.state), address.zip].compact.join(", ")

  .contact.details
    .first.contact
      .board.for.contact
        %h3 Relationships
        %h2
          = link_to @entity.company.name, @entity.company
        %h4 
          - if @entity.job_title
            = @entity.job_title
        %h5 
          Relationship to the Company
        %table.table-hover.table-condensed
          - @entity.company.internal_company_relationships.ordered_by_status_and_internal_company_name.each do |internal_company_relationship|
            %tr
              %td
                %span.bold 
                  = link_to internal_company_relationship.internal_company.name, internal_company_relationship.internal_company
              %td
                %span.light Role:
                %span.dark
                  = internal_company_relationship.role.text
                %br
              %td
                %span.light Status:
                %span.dark
                  = internal_company_relationship.record_status
                %br

      .board.for.contact
        %h3 User Account
        %table.table-hover.table-condensed
          %tr
            %td
              %span.light Account:
            %td
              - if @user && @user.errors.any?
                .alert.alert-danger
                  - @user.errors.full_messages.each do |message|
                    %p
                      = message

              - if @entity.user.present?
                %span.dark
                  = @entity.user.email
                  - if !@entity.user.invitation_accepted? && @current_user.admin?
                    (Pending confirmation)
                    = form_tag("#{re_invite_contact_url(@entity.id)}") do
                      %button.btn.btn-primary{ id: "btn_reinvite" } Reinvite
                      %span.label#reinvitation_result{ style: "display: none" }
              - elsif current_user.admin?
                %span.dark
                  = link_to "Invite user", new_invite_contact_url(@entity), remote: true, class: ""
          %tr
            %td
              %span.light Level:
            %td  
              %span.dark N/A
          %tr
            %td
              %span.light Module Access:
            %td  
              %span.dark None
  .contact.details
    .contact
      .board.for.contact.communications
        %h3
          Communications
          = link_to edit_section_contact_url(@entity), class: "btn-fam no-border", remote: true do
            %i.fa.fa-pencil
        %table.table-hover.table-condensed
          %tr
            %td 
              %span.light Do not email:
            %td
              %span.dark
                = human_boolean(@entity.do_not_email)
          %tr
            %td
              %span.light Do not mail:
            %td
              %span.dark
                = human_boolean(@entity.do_not_mail)
          %tr
            %td
              %span.light Birthday:
            %td
              %span.dark
                = @entity.birthday && l(@entity.birthday, format: :only_date_month)
          %tr
            %td
              %span.light Contest Participant:
            %td
              %span.dark
                = human_boolean(@entity.contest_participant)
          %tr
            %td
              %span.light Sources:
            %td
              %span.dark
                = @entity.contact_sources.to_sentence
      
      .board.for.contact.notes
        %h3
          Notes
          = link_to new_note_url(notable_id: @entity.id, notable_type: "Contact"), class: "btn-fam no-border", remote: true do
            %i.fa.fa-plus

        %ul.list-unstyled.notes
          - @entity.notes.each do |note|
            %li
              .note
                = simple_format(note.note)
              .meta.text-muted
                = l(note.updated_at)
                - if note.user #Imported from legacy data
                  = note.user.contacts.first.full_name
                = link_to "edit", edit_note_url(note), remote: true
                |
                = link_to "delete", note_url(note), data: { confirm: "Are you sure?", method: 'delete' }

app/views/contacts/success.js.haml
Turbolinks.visit('#{contact_url(@entity)}');

app/views/contacts/success_invite.js.haml
Turbolinks.visit('#{contact_url(@entity)}');