config/routes.rb
Jobrunner::Application.routes.draw do
  devise_for :users
  root to: redirect("/contacts")

  resources :activities
  resources :notes
  resources :contacts do
    member do
      get :edit_section
      patch :update_section
      get :new_invite
      post :re_invite
      post :invite
    end
  end

  resources :companies do
    member do
      get :edit_section
      patch :update_section
      patch :delete_company_logo
    end

    resources :contacts
  end
  
  namespace "api" do
    resources :company_types, defaults: { format: "json" }
    resources :companies, defaults: { format: "json" }
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_paper_trail
  include Archivable
  include Audited

  has_many :addresses, -> { order "created_at" }, dependent: :destroy, as: :addressable
  has_many :affiliate_affiliations, foreign_key: 'principal_id', dependent: :destroy, class_name: 'Affiliation'
  has_many :affiliates, -> { order "name" }, through: :affiliate_affiliations, source: :affiliate, class_name: 'Company'
  has_many :principal_affiliations, foreign_key: 'affiliate_id', dependent: :destroy, class_name: 'Affiliation'
  has_many :principals, through: :principal_affiliations, source: :principal, class_name: 'Company'

  has_many :internal_company_relationships, dependent: :destroy
  has_many :internal_companies, through: :internal_company_relationships, source: :internal_company, class_name: 'Company'
  has_many :contacts, -> { order "first_name" },  dependent: :destroy
  has_many :phone_numbers, -> { order "created_at ASC" }, as: :phonable, dependent: :destroy
  belongs_to :company_type

  accepts_nested_attributes_for :addresses, reject_if: lambda { |address| address[:address_line_1].blank? }, allow_destroy: true
  accepts_nested_attributes_for :phone_numbers, reject_if: lambda { |phone_number| phone_number[:phone_number].blank? }, allow_destroy: true
  accepts_nested_attributes_for :affiliate_affiliations, reject_if: lambda { |affiliation| affiliation[:affiliate_id].blank? }, allow_destroy: true
  accepts_nested_attributes_for :principal_affiliations, reject_if: lambda { |affiliation| affiliation[:principal_id].blank? }, allow_destroy: true
  accepts_nested_attributes_for :internal_company_relationships, reject_if: lambda { |relationship| relationship[:internal_company_id].blank? }, allow_destroy: true

  mount_uploader :company_logo, CompanyLogoUploader
  validates :name, presence: true, uniqueness: true

  scope :ordered_by_affiliate_name, -> { includes(affiliate_affiliations: :affiliate).order("companies.name") }
  scope :ordered_by_name, -> { order("companies.name") }
  scope :internal, -> { where(company_type_id: CompanyType.internal.id ) }

  def all_principal_and_affiliates
    (self.affiliates + self.principals).sort_by(&:name)
  end

  class << self
    def with_affiliation_affiliate_company_types
      Company.where("company_type_id IN (?)", CompanyType.affiliate_company_types)
    end

    def with_affiliation_principal_company_types
      Company.where("company_type_id IN (?)", CompanyType.principal_company_types)
    end

    def search(term)
      return Company.none if term.blank?
      term_like = "%#{term}%"
      where("companies.name ILIKE ?", term_like)
    end

    def affiliated_to_company(company_ids)
      includes(:principal_affiliations).references(:principal_affiliations).where('affiliations.principal_id IN (?)', company_ids).references(:affiliate_affiliations)
    end

    def with_company_types(company_type_ids)
      where(company_type_id: company_type_ids)
    end

    def with_internal_relationship_role(roles)
      includes(:internal_company_relationships).references(:internal_company_relationships).where('internal_company_relationships.role IN (?)', roles)
    end

    def eager_load_associations
      includes(:affiliates, :principals, :internal_companies, :company_type)
    end

    def relationship_with_company(company_ids)
      includes(:internal_company_relationships).references(:internal_company_relationships).where('internal_company_relationships.internal_company_id IN (?)', company_ids)
    end

    def with_affiliations_and_relationships_with_archived_status(archived_status)
      archived_status = [archived_status].flatten.map{ |status| status.to_s == "true" }
      includes([:principal_affiliations, :internal_company_relationships]).
        references([:principal_affiliations, :internal_company_relationships]).
        where("affiliations.archived IN (?) OR internal_company_relationships.archived IN (?)", archived_status, archived_status)
    end
  end

  def audit_meta
    {
      item_descriptor: "company #{self.name}",
      item_root_class: self.class,
      item_root_object_id: self.id
    }
  end
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  scope :ordered_by_name, -> { order("company_types.name") }

  def can_be_affiliation_affiliate?
    CompanyType.affiliate_company_types.include?(self)
  end

  def can_be_affiliation_principal?
    CompanyType.principal_company_types.include?(self)
  end

  def to_s
    self.name
  end

  def code
    self.name.underscore.gsub(" ", "_")
  end

  class << self
    def affiliate_company_types
      all_company_types.values_at("nonprofit", "commercial_mailer")
    end

    def list_manager_company_type
      all_company_types["list_manager"]
    end

    def principal_company_types
      all_company_types.values_at("agency")
    end

    def internal
      all_company_types["internal"]
    end

    def all_company_types
      return @all_company_types if @all_company_types
      @all_company_types = {}
      CompanyType.all.each do |company_type|
        @all_company_types[company_type.code] = company_type
      end
      @all_company_types
    end
  end
end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < ApiController
  def index
    company_type = CompanyType.all_company_types[params[:company_type_code]] if params[:company_type_code]
    companies = company_type.present? ? Company.where(company_type_id: company_type) : Company.all
    respond_with companies
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include SearchFiltersSaver
  include AddressParamsParser

  respond_to :html, :js, :csv
  
  ENTITY_PREFIX = "company"
  FILTER_ITEMS = [:a, :ac, :ct, :irr, :rc, :search, :name_sort]
  
  def index
    @entities, @entities_all_pages = apply_filters(@entities)
    respond_with(@entities)
  end

  def new
    @entity = Company.new(params[:company])
    respond_with(@entity)
  end

  def create
    @entity = Company.new(permitted_params)
    if @entity.save
      redirect_to company_url(@entity)
    else
      render(:new)
    end
  end

  def edit
    render(:new)
  end

  def update
    if @entity.update_attributes(permitted_params_with_country_parsed)
      redirect_to(company_url(@entity))
    else
      render(:new)
    end
  end

  def show
    @entities, @entities_all_pages = apply_filters(@entities)
    @entities_ids = @entities.map(&:id)
    set_saved_filters_new_page!
    respond_with(@entity)
  end

  def destroy
    @entity.destroy
    redirect_to companies_url_with_saved_filters
  end

  def edit_section
    @section = params[:section]
    respond_to do |format|
      format.js { render(:edit_section) }
    end
  end

  def update_section
    @section = params[:section]
    if @entity.update_attributes(permitted_params)
      render(:success)
    else
      render(:edit_section)
    end
  end

  def delete_company_logo
    @entity.remove_company_logo!
    @entity.save
    redirect_to edit_company_url(@entity)
  end

  private

  def permitted_params
    params.require(:company).permit(:name, :website, :phone, :company_logo, :company_type_id,
                                    affiliate_affiliations_attributes: [:id, :archived, :affiliate_id, :role, :_destroy],
                                    principal_affiliations_attributes: [:id, :archived, :principal_id, :role, :_destroy],
                                    internal_company_relationships_attributes: [:id, :archived, :internal_company_id, :role, :_destroy],
                                    addresses_attributes: [:id, :address_line_1, :address_line_2, :city, :state, :zip, :country, :_destroy],
                                    phone_numbers_attributes: [:id, :extension, :kind, :phone_number, :_destroy]
    )
  end

  def load_entities
    @entities = Company.all
    @entity = Company.includes(:internal_companies, :affiliates).find(params[:id]) if params[:id].present?
  end

  def apply_filters_concrete(source)
    source_filtered = get_saved_filters.has_key?(:search) ? source.search(get_saved_filters[:search]) : source
    source_filtered = source_filtered.with_affiliations_and_relationships_with_archived_status(get_saved_filters[:a]) if get_saved_filters.has_key?(:a)
    source_filtered = source_filtered.affiliated_to_company(get_saved_filters[:ac]) if get_saved_filters.has_key?(:ac)
    source_filtered = source_filtered.with_company_types(get_saved_filters[:ct]) if get_saved_filters.has_key?(:ct)
    source_filtered = source_filtered.with_internal_relationship_role(get_saved_filters[:irr]) if get_saved_filters.has_key?(:irr)
    
    source_filtered = source_filtered.relationship_with_company(get_saved_filters[:rc]) if get_saved_filters.has_key?(:rc)
    source_filtered = get_saved_filters[:name_sort] == "down" ? source_filtered.order("companies.name DESC") : source_filtered.order("companies.name ASC")
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  include BackForwardLinkGenerator
  include CountryStateDataSource
  
  def tooltip_text_for_filter(filter)
    {
      relationships: "Shows companies related to the selected internal company",
      roles: "Shows companies related to any internal company in the selected role",
      status: "Shows companies with the selected affiliation or relationship status",
      company_type: "Shows companies of the selected type",
      accounts_of: "Shows companies affiliated to the selected company"
    }[filter]
  end

  private 

  def entity_path
    ->(id) { company_path(id) } 
  end
end

app/views/companies/_address_fields.html.haml
.row
  #addresses
    = f.fields_for :addresses, (@entity.persisted? || @entity.addresses.present?) ? @entity.addresses : @entity.addresses.build, wrapper: false do |address_form|
      .col-md-4.fields
        .panel.panel-default
          .panel-heading
            .panel-title
              Address
          .panel-body
            = address_form.input :address_line_1, as: :string, placeholder: "Address Line 1", label: false
            = address_form.input :address_line_2, as: :string, placeholder: "Address Line 2", label: false
            .row
              .col-md-6
                = country_state_select address_form, "company"
                = address_form.input :city, placeholder: "City", label: false
              .col-md-6
                = address_form.input :zip, placeholder: "Zip", label: false

            = address_form.link_to_remove "Remove", class: "btn btn-danger"
  .col-md-4
    = f.link_to_add  "Add address", :addresses, class: "btn btn-default", data: { target: "#addresses" }

app/views/companies/_affiliations_table.html.haml
%h3
  = header
= link_to edit_section_company_url(@entity, section: edit_section), class: "btn-fam no-border", remote: true do
  %i.fa.fa-pencil

%table.table.table-hover
  %thead
    %tr
      %th Company
      %th Company Type
      %th Status
      %th Added
      %th Last Modified
  %tbody
    - affiliations.each do |affiliation|
      %tr
        %td
          = link_to affiliation.send(affiliation_relation).name, affiliation.send(affiliation_relation)
        %td
          = affiliation.send(affiliation_relation).company_type
        %td
          = affiliation.record_status
        %td
          = l(affiliation.created_at, format: :only_date)
        %td
          = l(affiliation.updated_at, format: :only_date)

app/views/companies/_company.html.haml
%tr
  %td
    = image_tag company.company_logo.mini_thumb.url, alt: company.name
  %td
    = link_to company.name, company_url(company)
  %td
    %ul.list-unstyled
      - company.internal_company_relationships.each do |relationship|
        %li
          = relationship.internal_company.name
          %code
            = "#{(relationship.role.text)}"
  %td
    %ul.list-unstyled
      - company.all_principal_and_affiliates.each do |company|
        %li
          = company.name
          %code
            = company.company_type.name

app/views/companies/_edit_affiliates.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{ "data-dismiss" => "modal", type: "button" } ×
      %h2.modal-title
        Manage Affiliates
    #modal-form
      = simple_nested_form_for @entity, url: update_section_company_url(@entity, section: "affiliates"), html: { class: "form-horizontal" }, remote: true do |f|
        .modal-body
          - if @entity.errors.any?
            .alert.alert-danger
              %a.close{ "data-dismiss" => "alert", href: "#" } ×
              - @entity.errors.full_messages.each do |message|
                %p
                  = message
          .row
            .col-md-10.col-md-offset-1
              .row
                .col-md-12
                  %table.table
                    %thead
                      %tr
                        %th
                          Company
                        %th
                          Inactive
                        %th
                    %tbody#affiliation-fields
                      = f.fields_for :affiliate_affiliations, @entity.affiliate_affiliations.present? ? @entity.affiliate_affiliations.ordered_by_affiliate_name : @entity.affiliate_affiliations.build, wrapper: false do |affiliation_form|
                        %tr.fields
                          %td
                            .col-md-12
                              = affiliation_form.input :affiliate_id, collection: Company.with_affiliation_affiliate_company_types.ordered_by_name.map{ |c| ["#{c.name} (#{c.company_type})", c.id] }, include_blank: "Select company" , label: false
                          %td
                            .col-md-12
                              = affiliation_form.input :archived, label: false, wrapper: false
                          %td
                            .col-md-12
                              = affiliation_form.link_to_remove "Remove", class: "btn btn-danger btn-xs", data: { confirm: "Are you sure you want to delete this affiliate?"}

                  = f.link_to_add  "Add affiliate", :affiliate_affiliations, class: "btn btn-default", data: { target: "#affiliation-fields" }

        .modal-footer
          %button.btn.btn-default{ "data-dismiss" => "modal", type: "button" } Close
          = f.submit "Save", class: "btn btn-primary", data: { toggle: "button", "loading-text" => "Saving" }

app/views/companies/_edit_internal_company_relationships.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{ "data-dismiss" => "modal", type: "button" } ×
      %h2.modal-title
        Manage Relationships
    #modal-form
      = simple_nested_form_for @entity, url: update_section_company_url(@entity, section: "internal_company_relationships"), html: { class: "form-horizontal" }, remote: true do |f|
        .modal-body
          - if @entity.errors.any?
            .alert.alert-danger
              %a.close{ "data-dismiss" => "alert", href: "#" } ×
              - @entity.errors.full_messages.each do |message|
                %p
                  = message
          - if @success_message
            .alert.alert-success
              %a.close{ "data-dismiss" => "alert", href: "#" } ×
              %h4
                = @success_message

          .row
            .col-md-10.col-md-offset-1
              .row
                = render "internal_company_relationships_fields", f: f
        .modal-footer
          %button.btn.btn-default{ "data-dismiss" => "modal", type: "button" } Close
          = f.submit "Save", class: "btn btn-primary", data: { toggle: "button", "loading-text" => "Saving" }

app/views/companies/_edit_principals.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{ "data-dismiss" => "modal", type: "button" } ×
      %h2.modal-title
        Manage Agencies
    #modal-form
      = simple_nested_form_for @entity, url: update_section_company_url(@entity, section: "principals"), html: { class: "form-horizontal" }, remote: true do |f|
        .modal-body
          - if @entity.errors.any?
            .alert.alert-danger
              %a.close{ "data-dismiss" => "alert", href: "#" } ×
              - @entity.errors.full_messages.each do |message|
                %p
                  = message
          .row
            .col-md-10.col-md-offset-1
              .row
                .col-md-12
                  %table.table
                    %thead
                      %tr
                        %th
                          Company
                        %th
                          Inactive
                        %th
                    %tbody#affiliation-fields
                      = f.fields_for :principal_affiliations, @entity.principal_affiliations.present? ? @entity.principal_affiliations.ordered_by_principal_name : @entity.principal_affiliations.build, wrapper: false do |affiliation_form|
                        %tr.fields
                          %td
                            .col-md-12
                              = affiliation_form.input :principal_id, collection: Company.with_affiliation_principal_company_types.ordered_by_name.map{ |c| ["#{c.name} (#{c.company_type})", c.id] }, include_blank: "Select company" , label: false
                          %td
                            .col-md-12
                              = affiliation_form.input :archived, label: false, wrapper: false
                          %td
                            .col-md-12
                              = affiliation_form.link_to_remove "Remove", class: "btn btn-danger btn-xs", data: { confirm: "Are you sure you want to delete this?"}

                  = f.link_to_add  "Add Agency", :principal_affiliations, class: "btn btn-default", data: { target: "#affiliation-fields" }

        .modal-footer
          %button.btn.btn-default{ "data-dismiss" => "modal", type: "button" } Close
          = f.submit "Save", class: "btn btn-primary", data: { toggle: "button", "loading-text" => "Saving" }

app/views/companies/_internal_company_relationships_fields.html.haml
.row
  .col-md-12
    %table.table
      %thead
        %tr
          %th
            Company
          %th
            Role
          %th
            Inactive
          %th
      %tbody#internal-company-relationships-fields
        = f.fields_for :internal_company_relationships, (@entity.persisted? || @entity.internal_company_relationships.present?) ? @entity.internal_company_relationships.ordered_by_status_and_internal_company_name : @entity.internal_company_relationships.build, wrapper: false do |relationship_form|
          %tr.fields
            %td
              .col-md-12
                = relationship_form.input :internal_company_id, collection: Company.internal, include_blank: "Select company", label: false
            %td
              .col-md-12
                = relationship_form.input :role, collection: InternalCompanyRelationship.role.options, label: false
            %td
              .col-md-12
                = relationship_form.input :archived, label: false, wrapper: false
            %td
              .col-md-12
                = relationship_form.link_to_remove "Remove", class: "btn btn-danger btn-xs", data: { confirm: "Are you sure you want to delete this relationship?"}

    = f.link_to_add  "Add relationship", :internal_company_relationships, class: "btn btn-default", data: { target: "#internal-company-relationships-fields" }

app/views/companies/_phone_number_fields.html.haml
.row.top-buffer-15
  #phone_numbers
    = f.fields_for :phone_numbers, (@entity.persisted? || @entity.phone_numbers.present?) ? @entity.phone_numbers : @entity.phone_numbers.build, wrapper: false do |phone_number_form|
      .col-md-4.fields
        .panel.panel-default
          .panel-heading
            .panel-title
              Phone number
          .panel-body
            = phone_number_form.input :kind, collection: PhoneNumber.kind.options, include_blank: false, label: false
            .row
              .col-md-8
                = phone_number_form.input :phone_number, placeholder: "Phone Number", label: false, input_html: { data: "phone-number-input", autocomplete: "off" }
              .col-md-4
                = phone_number_form.input :extension, placeholder: "Extension", label: false, input_html: { data: "phone-number-extension-input", autocomplete: "off" }
            = phone_number_form.link_to_remove "Remove", class: "btn btn-danger"
  .col-md-4
    = f.link_to_add  "Add phone number", :phone_numbers, class: "btn btn-default", data: { target: "#phone_numbers" }

app/views/companies/edit_section.js.haml
$('#page-modal').html('#{j(render("edit_#{@section}"))}').modal();

app/views/companies/index.csv.haml
- require 'csv'

- max_relationships = @entities.map{ |c| c.internal_company_relationships.size }.max
- content = CSV.generate do |csv|
  - csv << (["Company Name", "Company Type", "Address", "Address 2", "City", "State", "Zip", "Country", "Website", "Primary Phone"] + max_relationships.times.map{ "Relationship" })
  - @entities.each do |company|
    - address = company.addresses.first || Address.new
    - phone_number = company.phone_numbers.first || PhoneNumber.new
    - csv << ([company.name, company.company_type, address.address_line_1, address.address_line_2, address.city, address.state, address.zip, address.country.upcase, company.website, phone_number] + company.internal_company_relationships.map{ |company_relationship| "#{company_relationship.internal_company.name} - #{company_relationship.role.text} #{ ' - ' + company_relationship.record_status if company_relationship.archived?}" })

= raw content

app/views/companies/index.html.haml
.index.content
  = render "action_panel", search_url: companies_url, csv_export_url: companies_url(params.merge(format: 'csv'))
  .contacts.holder
    %table.table.for.table-hover
      %thead
        %tr
          %th
          %th.sortable
            - if(params[:name_sort] == "down")
              = link_to companies_url(params.merge(name_sort: "up")) do
                Name
                %i.fa.fa-angle-down
            - else
              = link_to companies_url(params.merge(name_sort: "down")) do
                Name
                %i.fa.fa-angle-up
          %th
            Relationship(s)
          %th
            Affiliation(s)
      %tbody
        %tr
          %td.add.a.company{ colspan: 5 }
            .wrap
              %i.fa.fa-plus
              = link_to "Add a new company", new_company_url
      %tbody#companies-listing
        = render @entities
    #companies-pagination
      = paginate(@entities)
.profile.on.listing.pages
  = render "profile"

  = content_for :view_specific_filters do
    %h3.filter.header
      = link_to 'javascript:void(0)', data: { toggle: "collapse", target: "#affiliations-filter ul" }, class: "#{'collapsed' if params[:ac].blank?}" do
        Accounts of
        %i.glyphicon.glyphicon-chevron-up.pull-right
        %i.glyphicon.glyphicon-chevron-down.pull-right
        = button_tag "?", data: { toggle: "tooltip", title: tooltip_text_for_filter(:accounts_of) }, class: "btn btn-link btn-xs filter-help"

    .filter.wrapper#affiliations-filter
      %ul.list.default.list-unstyled{ class: "#{'collapse' if params[:ac].blank?}" }
        - Company.with_affiliation_principal_company_types.ordered_by_name.each do |principal|
          %li.checkbox
            = check_box_tag "affiliation_filter[company_ids]", principal.id, (params[:ac] || []).include?(principal.id.to_s)
            = principal.name

  = render "companies_contacts_shared/filter_sidebar"

app/views/companies/new.html.haml
.show.content
  .go.and.profile
    .go.back
      = link_to companies_url_with_saved_filters do
        %span.glyphicon.glyphicon-chevron-left
        Back to Companies
    .profile
      = render "profile"

  .company.details
    %h1
      - if @entity.persisted?
        = "Edit #{@entity.name}"
      - else
        New Company

    = simple_nested_form_for @entity do |f|
      .row
        .col-md-4
          %h2
            Profile
          .panel.panel-default
            .panel-body
              = f.input :name, placeholder: "Company Name", label: false
              = f.input :website, placeholder: "Website", label: false
              = f.input :company_type_id, collection: CompanyType.all, include_blank: "Company Type", label: false
              = f.input :company_logo
              - if @entity.company_logo.present?
                = image_tag @entity.company_logo.url
                = link_to "x", delete_company_logo_company_url , class: "btn btn-danger btn-xs", data: { method: "patch" }

      .row
        .col-md-12
          %h2
            Contact Info
          = render "address_fields", f: f
          = render "phone_number_fields", f: f

      %br
      .form-group
        = link_to "Back", back_url_or(companies_url_with_saved_filters), class: "btn btn-default"
        = f.submit "Save", class: "btn btn-primary"

app/views/companies/show.html.haml
.show.content
  .company.intro
    .neat-row.company-action
      .go.back
        = link_to companies_url_with_saved_filters do
          %span.glyphicon.glyphicon-chevron-left
          Back to Companies
      .profile-container
        = render "profile"      
    .company.logo
      = image_tag @entity.company_logo.url, alt: @entity.name
    .company.info.pull-right
      .company.name
        = link_to_previous_entity("Previous company")
        = @entity.name
        = link_to_next_entity("Next company")
        %span.label{ style: "white-space: normal;" }
          &mdash; 
          = @entity.company_type
        = link_to company_url(@entity), class: "btn-fam pull-right err", data: { confirm: "Are you sure you want to delete the company '#{@entity.name}'?", method: 'delete' } do
          %i.fa.fa-trash-o
          %span.action Delete
        = link_to edit_company_url(@entity), class: "btn-fam pull-right" do
          %i.fa.fa-pencil
          %span.action Edit
      .secondary.company.info
        .col-sm-6
          %span.label Address
          - @entity.addresses.each do |address|
            .address
              = [address.address_line_1, address.address_line_2, address.city, address.state, address.zip].compact.map(&:to_s).join(", ")
        .col-sm-3
          %span.label Phone
          = @entity.phone_numbers.map(&:to_s).join("<br>").html_safe
        .col-sm-3
          %span.label Web
          %a{href: "http://#{@entity.website}"}
            = @entity.website
  .company.details
    .first.company.row
      .col-sm-12
        .board.for.company
          %h3 Relationships
          = link_to edit_section_company_url(@entity, section: "internal_company_relationships"), class: "btn-fam no-border", remote: true do
            %i.fa.fa-pencil

        %table.table-hover.table-condensed
          %thead
            %tr
              %th Company
              %th Role(s)
              %th Status
              %th Added
              %th Last Modified
          %tbody
            - @entity.internal_company_relationships.ordered_by_status_and_internal_company_name.each do |relationship|
              %tr
                %td
                  = link_to relationship.internal_company.name, relationship.internal_company
                %td
                  = relationship.role.text
                %td
                  = relationship.record_status
                %td
                  = l(relationship.created_at, format: :only_date)
                %td
                  = l(relationship.updated_at, format: :only_date)

    .second.company.row
      .col-sm-12
        .board.for.company
          - if @entity.company_type.try(:can_be_affiliation_principal?)
            = render "affiliations_table", header: "Affiliates", affiliations: @entity.affiliate_affiliations.ordered_by_affiliate_name, edit_section: "affiliates", affiliation_relation: :affiliate
          - elsif @entity.company_type.try(:can_be_affiliation_affiliate?)
            = render "affiliations_table", header: "Managed By", affiliations: @entity.principal_affiliations.ordered_by_principal_name, edit_section: "principals", affiliation_relation: :principal

    .third.company.row
      .col-sm-12
        .board.for.company
          %h3 People
          %table.table.table-hover
            %thead
              %tr
                %th Name
                %th Title
                %th Email
                %th Phone
                %th Status
                %th Last Modified
            %tbody
              %tr
                %td.add.a.contact{ colspan: 6 }
                  .wrap
                    %i.fa.fa-plus
                    = link_to "Add a new contact", new_company_contact_url(@entity)
              - @entity.contacts.each do |contact|
                %tr
                  %td
                    = link_to contact.full_name, company_contact_url(@entity, contact)
                  %td
                    = contact.job_title
                  %td
                    = contact.emails.map{ |email| mail_to(email) }.join("<br />").html_safe
                  %td
                    = contact.phone_numbers.map(&:to_s).join(",")
                  %td
                    = contact.record_status
                  %td
                    = l(contact.updated_at, format: :only_date)

app/views/companies/success.js.haml
Turbolinks.visit('#{company_url(@entity)}');